[env:eliot]
platform = ststm32@19.0.0
board = eliot_core
framework = mbed
build_type = debug

; Tool di caricamento e debug
debug_tool = stlink
upload_protocol = stlink
debug_init_break = tbreak main

; Flags di compilazione
build_flags = 
    -Wall 
    -Wextra

; Monitor Seriale
monitor_speed = 115200

; Fix compatibilità Python per il build system Mbed
extra_scripts = pre:scripts/mbedAppCompat.py